server:
  port: 8890



spring:
  application:
    name: consumer01


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

