spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loneylee/opps-files.git

server:
  port: 8888



#  spring.cloud.config.server.git.uri：配置git仓库位置
#  spring.cloud.config.server.git.searchPaths：配置仓库路径下的相对搜索位置，可以配置多个
#  spring.cloud.config.server.git.username：访问git仓库的用户名
#  spring.cloud.config.server.git.password：访问git仓库的用户密码

#URL与配置文件的映射关系如下：
#
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties